### ISSUE TITLE
Naming the model file in the repository

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-modelrepository-plugin2#1]
In coArchi 1 a model's file was automatically named `temp.archimate` and stored in the `.git` directory of the local git repository to keep it out of the way of the grafico files in the working tree directory.

~In coArchi 2 (this project) we will be storing the model file "as is" in the working tree directory. As we are storing one model file per git repo we could name the file something like `model.archimate`.~

~Perhaps the `*.archimate` file could be named to something that the user wants? But I'm not sure whether this is necessary or  useful as the Collaboration Workspace View displays the model's name anyway (this is now stored in the `config` file when the user saves the model). And it's probably not a good idea to allow the user to rename it.~

@jbsarrodie Thoughts?

Edit - it is `model.xml` in the working directory and `model.archimate` in the `.git` directory. This will stop the user from trying to open the `model.xml` file, they should only open the `model.archimate` file.

**Comment by jbsarrodie** [comment]
> we could name the file something like `model.archimate`.

I was thinking the same. That's simple and explicite.

**Comment by Phillipus** [comment]
This is solved in latest work done on coArchi 2.
