### ISSUE TITLE
I'm over-excited

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-modelrepository-plugin2#3]
This issue needs to be addressed immediately.

My analysis of the coArchi code and the changes that we will make in coArchi 2 together with the commits in this new project makes me over-excited for what will be possible.

Suggested fix - one or two beers.

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/86519358-662fa300-be3a-11ea-8608-9f6b1e9db274.png)

**Comment by Phillipus** [comment]
Closing as "fixed", Cheers!
