### ISSUE TITLE
Use Eclipse's Proxy Network plug-ins and Secure Storage

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-modelrepository-plugin2#7]
Some quick notes about using Eclipse's in-built support for Proxy networking and secure storage...

## Proxy

To get this:

![network_page](https://user-images.githubusercontent.com/600504/136058695-5cd33c40-374d-4358-8f46-88372edc2b4f.png)

We need these:

`org.eclipse.core.net`
`org.eclipse.ui.net`

Annoyingly the preference page is tied to the `org.eclipse.ui.preferencePages.Workbench` parent category and you get stuff written to the log:

```
Invalid preference category path:
   org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.ui.net, page: org.eclipse.ui.net.NetPreferences)
```

And this:

```
!ENTRY org.eclipse.core.net 1 0 2021-10-05 15:52:15.724
!MESSAGE System property https.proxyHost is not set but should be 192.168.10.1.

!ENTRY org.eclipse.core.net 1 0 2021-10-05 15:52:15.725
!MESSAGE System property https.proxyPort is not set but should be 9999.
```

Same thing happens with XMind, as they use it too.

## Secure storage

Eclipse has its own secure key-ring. The Proxy settings above are stored in it.

This needs investigating:

`org.eclipse.equinox.security.storage.ISecurePreferences`

**Comment by Phillipus** [comment]
There's a new branch in the main Archi code, `security-net`. This stuff only shows up in Preferences, not actually used anywhere in code yet.

**Comment by jbsarrodie** [comment]
> So, unless there are any gotchas we may be able to use Eclipse's Proxy, SSH and Secure Storage frameworks in Archi itself and they can be used by coArchi and any other plug-ins. 🙏

I see two potential issues:
- Some companies will not want to rely on the "Windows Integration", and the "UI Prompt" doesn't seem to allow definition of password complexity and expiration. Maybe we can reuse current coArchi code into a new "Enhanced UI Prompt" ?
- By moving security out of coArchi and into main Archi code, any plugin can get access to any stored passwords. Is it possible to make sure a plugin only get access to its "own" passwords ?
